sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  # Build Testing and Production images
  - docker build -t vidalignacio/stock-client-service:test -f ./client-service/Dockerfile.dev ./client-service

  # Run Testing with Dev images
  - docker run -e CI vidalignacio/stock-client-service:test npm run test

after_success:
  # Build Production images
  - docker build -t vidalignacio/stock-calculator-service:latest -t vidalignacio/stock-calculator-service:$(git rev-parse HEAD) ./calculator-service
  - docker build -t vidalignacio/stock-client-service:latest -t vidalignacio/stock-client-service:$(git rev-parse HEAD) ./client-service
  - docker build -t vidalignacio/stock-orchestrator-service:latest -t vidalignacio/stock-orchestrator-service:$(git rev-parse HEAD) ./orchestrator-service
  - docker build -t vidalignacio/stock-redis-service:latest -t vidalignacio/stock-redis-service:$(git rev-parse HEAD) ./redis-service
  - docker build -t vidalignacio/stock-pricer-service:latest -t vidalignacio/stock-pricer-service:$(git rev-parse HEAD) ./pricer-service
  
  #Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push vidalignacio/stock-calculator-service:latest
  - docker push vidalignacio/stock-client-service:latest
  - docker push vidalignacio/stock-pricer-service:latest
  - docker push vidalignacio/stock-orchestrator-service:latest
  - docker push vidalignacio/stock-redis-service:latest

  - docker push vidalignacio/stock-calculator-service:$(git rev-parse HEAD)
  - docker push vidalignacio/stock-client-service:$(git rev-parse HEAD)
  - docker push vidalignacio/stock-pricer-service:$(git rev-parse HEAD)
  - docker push vidalignacio/stock-orchestrator-service:$(git rev-parse HEAD)
  - docker push vidalignacio/stock-redis-service:$(git rev-parse HEAD)

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: stock
  env: stock-env
  bucket_name: elasticbeanstalk-eu-west-2-571507774031
  bucket_path: stock-container
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
