sudo: required
language: node_js
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  # Build Production images
  - docker build -t vidalignacio/stock-calculator-service:latest -t vidalignacio/stock-calculator-service:SHA ./calculator-service
  - docker build -t vidalignacio/stock-client-service:latest -t vidalignacio/stock-client-service:SHA ./client-service
  - docker build -t vidalignacio/stock-orchestrator-service:latest -t vidalignacio/stock-orchestrator-service:SHA ./orchestrator-service
  - docker build -t vidalignacio/stock-redis-service:latest -t vidalignacio/stock-redis-service:SHA ./redis-service
  - docker build -t vidalignacio/stock-pricer-service:latest -t vidalignacio/stock-pricer-service:SHA ./pricer-service

after_success:
  #Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push vidalignacio/stock-calculator-service:latest
  - docker push vidalignacio/stock-client-service:latest
  - docker push vidalignacio/stock-pricer-service:latest
  - docker push vidalignacio/stock-orchestrator-service:latest
  - docker push vidalignacio/stock-redis-service:latest

  - docker push vidalignacio/stock-calculator-service:SHA
  - docker push vidalignacio/stock-client-service:SHA
  - docker push vidalignacio/stock-pricer-service:SHA
  - docker push vidalignacio/stock-orchestrator-service:SHA
  - docker push vidalignacio/stock-redis-service:SHA

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: stock
  env: stock-env
  bucket_name: elasticbeanstalk-eu-west-2-571507774031
  bucket_path: stock-container
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
