version: "3"

services:
  calculator:
    container_name: calculator
    image: stocky-calculator:dev
    restart: always
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 80"
    environment:
      - docker.env
    volumes:
      - ./calculator-service:/app
    ports:
      - "8080:80"

  client:
    container_name: client
    image: stocky-client:dev
    restart: always
    environment:
      - docker.env
    volumes:
      - /app/node_modules
      - ./client-service:/app
    ports:
      - "3000:3000"
    
