version: "3"

services:
  calculator:
    container_name: calculator
    image: stocky-calculator-service:dev
    restart: always
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 80"
    environment:
      - docker.env
    volumes:
      - ./calculator-service:/app
    ports:
      - "8080:80"
      
  pricer:
    container_name: pricer
    image: stocky-pricer-service:dev
    restart: always
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 3000"
    environment:
      - docker.env
    volumes:
      - ./pricer-service:/app
    ports:
      - "3010:3000"

  client:
    container_name: client
    image: stocky-client-service:dev
    restart: always
    environment:
      - docker.env
    volumes:
      - /app/node_modules
      - ./client-service:/app
    ports:
      - "3000:3000"

  orchestrator:
    container_name: orchestrator
    image: stocky-orchestrator-service:dev
    restart: always
    command: "npm run dev"
    environment:
      - docker.env
    volumes:
      - /app/node_modules
      - ./orchestrator-service:/app
    ports:
      - "5000:3000"
    depends_on: 
      - redis

  redis:
    container_name: redis
    image: stocky-redis-service:dev
    restart: always

  redis-admin:
    image: erikdubbelboer/phpredisadmin
    container_name: redis-admin
    environment:
        - REDIS_1_HOST=redis
    ports:
        - "6379:80"
    depends_on:
        - redis