version: "3"

services:
  client:
    container_name: test-client
    image: stock-client-service:dev
    command: npm run test
    env_file:
      - docker.env
    volumes:
      - /app/node_modules
      - ./client-service:/app