version: "3"

services:
  pricer:
    container_name: pricer
    image: stocky-pricer:dev
    restart: always
    command: ["npm", "run", "dev"]
    environment:
      - docker.env
    # depends_on:
    #   - mongo:dev
    volumes:
      - /app/node_modules
      - ./pricer:/app
  calculator:
    container_name: calculator
    image: stocky-calculator:dev
    restart: always
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 80"
    environment:
      - docker.env
    # depends_on:
    #   - mongo:dev
    volumes:
      - /app/node_modules
      - ./calculator:/app
    ports:
      - "80:80"
  client:
    container_name: client
    image: stocky-client:dev
    restart: always
    environment:
      - docker.env
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

