apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
type: Opaque
stringData:
  MONGO_DB_SERVICE: mongo-service
  NODE_ENV: production
  MONGO_CLUSTER: cluster0-r5v2n.mongodb.net/
  MONGO_USER: Ignacio
  MONGO_PASSWORD: Lirios89
  JWT_DURATION: 10h
  JWT_SECRET: thismysupersecretindev
  AWS_KEY: AKIAYKEEESJH5QUHSN7J
  AWS_SECRET: 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
  S3_BUCKET_NAME: arawa-management
  EMAIL_USER: leioapropertyltd@gmail.com
  EMAIL_PASSWORD: Lirios89
