export const STOCK_PRICE_URL = '/stockPrice'
export const STOCK_PRICE_HISTORY_URL = '/stockPriceHistory'
export const STOCK_PRICE_CHANGE_URL = '/stockPriceChange'
export const STOCK_RISK_RETURN_URL = '/stockRiskReturn'
export const STOCK_METRICS = '/financialMetrics'