// Stock Resources
export const FETCH_STOCK_DETAILS = 'FETCH_STOCK_DETAILS'
export const STOCK_DETAILS_LOADING = 'STOCK_DETAILS_LOADING'
export const STOCK_DETAILS_NOT_LOADING = 'STOCK_DETAILS_NOT_LOADING'


export const FETCH_STOCK_PRICE_HISTORY = 'FETCH_STOCK_PRICE_HISTORY'
export const STOCK_PRICE_HISTORY_LOADING = 'STOCK_PRICE_HISTORY_LOADING'
export const STOCK_PRICE_HISTORY_NOT_LOADING = 'STOCK_PRICE_HISTORY_NOT_LOADING'


export const FETCH_STOCK_METRICS = 'FETCH_STOCK_METRICS'
export const STOCK_METRICS_LOADING = 'STOCK_METRICS_LOADING'
export const STOCK_METRICS_NOT_LOADING = 'STOCK_METRICS_NOT_LOADING'

export const FETCH_STOCK_OPTIONS = 'FETCH_STOCK_OPTIONS'
export const STOCK_OPTIONS_LOADING = 'STOCK_OPTIONS_LOADING'
export const STOCK_OPTIONS_NOT_LOADING = 'STOCK_OPTIONS_NOT_LOADING'


// Portfolio Resources
export const FETCH_PORTFOLIO_METRICS = 'FETCH_PORTFOLIO_METRICS'
export const PORTFOLIO_METRICS_LOADING = 'PORTFOLIO_METRICS_LOADING'
export const PORTFOLIO_METRICS_NOT_LOADING = 'PORTFOLIO_METRICS_NOT_LOADING'


// Efficient Frontier
export const FETCH_EFFICIENT_FRONTIER = 'FETCH_EFFICIENT_FRONTIER'
export const EFFICIENT_FRONTIER_LOADING = 'EFFICIENT_FRONTIER_LOADING'
export const EFFICIENT_FRONTIER_NOT_LOADING = 'EFFICIENT_FRONTIER_NOT_LOADING'
export const RESET_EFFICIENT_FRONTIER = 'RESET_EFFICIENT_FRONTIER'


// Generic Resouces
export const SET_ERROR = 'SET_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'


// Tickers
export const ADD_TICKER = 'ADD_TICKER'
export const REMOVE_TICKER = 'REMOVE_TICKER'

// REDUCER THAT REQUIRE APIs
export const RESET_REDUCER = 'RESET_REDUCER'

// USER
export const LOGIN = 'LOGGIN'
export const LOGOUT = 'LOGOUT'

