// Stock Resources
export const FETCH_CARDS = 'FETCH_CARDS'
export const SELECT_STOCK = 'SELECT_STOCK'
export const REMOVE_STOCK = 'REMOVE_STOCK'
export const FETCH_STOCK_PRICE_HISTORY = 'FETCH_STOCK_PRICE_HISTORY'
export const FETCH_STOCK_PRICE_CHANGE = 'FETCH_STOCK_PRICE_CHANGE'
export const FETCH_STOCK_PRICE_NORMALIZED = 'FETCH_STOCK_PRICE_NORMALIZED'
export const FETCH_STOCK_RISK_RETURN = 'FETCH_STOCK_RISK_RETURN'


// Generic Resouces
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE'
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE'
export const SET_ERROR = 'SET_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'


// Portfolio Resources
export const FETCH_PORTFOLIO_RISK_RETURNS = 'FETCH_PORTFOLIO_RISK_RETURNS'